# Generated by Django 5.1.2 on 2024-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='month_added',
            field=models.DateTimeField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1),
        ),
    ]
